### ISSUE TITLE
TypeError: this.template is not a function

### ISSUE THREAD

**Issue by tarmolov** [d4rkr00t/badgs#54]
При переходе на версию `1.1.0` у меня все сломалось.

```
TypeError: this.template is not a function
    at Badgs.render (/Users/hevil/Yandex/test/node_modules/badgs/lib/index.js:164:17)
    at /Users/hevil/Yandex/test/server/middlewares/badge.js:21:32
    at Array.<anonymous> (/Users/hevil/Yandex/test/node_modules/vow/lib/vow.js:699:56)
    at Immediate.callFns [as _onImmediate] (/Users/hevil/Yandex/test/node_modules/vow/lib/vow.js:23:35)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

```
hevil@hevil-osx $ node --version
v5.10.1
```

**Comment by d4rkr00t** [comment]
Спасибо я посмотрю :)

**Comment by d4rkr00t** [comment]
Пофиксилось тут — https://github.com/d4rkr00t/badgs/pull/53

**Comment by tarmolov** [comment]
Спасибо. Помогло)
